version: '2.3'
networks:
  web: 
    external: true

services:

  nginx:
    build: ./nginx
    image: wisecoding/nginx-proxy
    networks:
      - web
    #user: nginx
    env_file:
      - ./config.env
    volumes:
      - "${BASE_DIR}/data/nginx/conf.d/:/etc/nginx/conf.d"
      - "${BASE_DIR}/data/nginx/ssl:/etc/nginx/ssl"
      - "${BASE_DIR}/data/letsencrypt:/etc/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    build: ./certbot
    image: wisecoding/certbot
    user: certbot
    networks:
      - web
    env_file:
      - ./config.env
    volumes:
      - "${BASE_DIR}/data/letsencrypt:/etc/letsencrypt"
    depends_on:
      - nginx

