version: '2.3'
networks:
  web: 
    external: true

services:

  nginx:
    image: wisecoding/nginx-proxy
    container_name: nginx
    build: ./nginx
    networks:
      - web
    env_file:
      - ./config.env
    volumes:
      - "${BASE_DIR}/config.env:/etc/config.env"
      - "${BASE_DIR}/data/nginx/conf.d/:/etc/nginx/conf.d"
      - "${BASE_DIR}/data/nginx/ssl:/etc/nginx/ssl"
      - "${BASE_DIR}/data/letsencrypt:/etc/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    image: wisecoding/certbot
    container_name: certbot
    build: ./certbot
    #user: certbot
    restart: always
    networks:
      - web
    env_file:
      - ./config.env
    volumes:
      - "${BASE_DIR}/config.env:/etc/config.env"
      - "${BASE_DIR}/data/letsencrypt:/etc/letsencrypt"
    depends_on:
      - nginx

